import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { ParsedUrlQuery } from 'querystring'
import { paths, populatePath, PopulatedPath, hasNextPaths } from '../../data'
import { Header, Main, Column, H1, H2 } from '../../src/ui'
import { Resources, Paths } from '../../src/path'

interface Params extends ParsedUrlQuery {
  pathName: string
}

interface StaticProps {
  path: PopulatedPath
}

export const getStaticPaths: GetStaticPaths = async () => {
  const staticPaths = Object.keys(paths).map((pathName) => ({
    params: { pathName },
  }))

  return { paths: staticPaths, fallback: false }
}

export const getStaticProps: GetStaticProps<StaticProps, Params> = async ({
  params,
}) => {
  const path = paths[params!.pathName]
  const populatedPath = populatePath(path)

  return {
    props: {
      path: populatedPath,
    },
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default function PathPage({ path }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <Column>
          <H1>
            The <u>{path.title}</u> learning path
          </H1>
        </Column>

        <Column>
          <Resources resources={path.resources} />
        </Column>

        {hasNextPaths(path) && (
          <Column>
            <aside>
              <H2>You could continue with</H2>
              <Paths paths={path.next} />
            </aside>
          </Column>
        )}
      </Main>
    </div>
  )
}
