import { GetStaticPaths, GetStaticProps, GetStaticPropsContext, InferGetStaticPropsType } from 'next'
import { ParsedUrlQuery } from 'querystring'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import data, { Resources } from '../data'

interface Params extends ParsedUrlQuery {
    resourceType: string
}

interface StaticProps {
    resources: Resources
}

export const getStaticPaths: GetStaticPaths = async () => {
    const paths = Object.keys(data).map((resourceType) => ({
        params: { resourceType }
    }))

    return { paths, fallback: false }
}

export const getStaticProps: GetStaticProps<StaticProps, Params> = async ({ params }) => {
    const resources = data[params!.resourceType]

  return {
    props: {
      resources
    }
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default function Home({ resources }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Javascript
        </h1>

        <div className={styles.grid}>
          <ul>
            {Object.values(resources).map((resource) => <li key={resource.url}>
                <a href={resource.url} target="_blank" rel="noreferrer">{resource.title}</a>
            </li>)}
          </ul>
        </div>
      </main>

    </div>
  )
}
