import Head from 'next/head'
import { GetStaticPropsContext, InferGetStaticPropsType } from 'next'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import resources from '../data'

export const getStaticProps = async (_: GetStaticPropsContext) => {
  return {
    props: {
      resources
    }
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default function Home({ resources }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>

        <div className={styles.grid}>
          <ul>
            {Object.entries(resources).map(([resourceType]) => <li key={resourceType}>{resourceType}</li>)}
          </ul>
        </div>
      </main>

    </div>
  )
}
