import { GetStaticPropsContext, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import paths from '../data/paths'

export const getStaticProps = async (_: GetStaticPropsContext) => {
  return {
    props: {
      paths
    }
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default function Home({ paths }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>

        <div className={styles.grid}>
          <ul>
            {Object.entries(paths).map(([pathName]) => <li key={pathName}>
              <Link href={`paths/${pathName}`}>
                <a>{pathName}</a>
              </Link>
            </li>)}
          </ul>
        </div>
      </main>

    </div>
  )
}
