name: 'Preview'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # to prevent a hanging process from using all CI minutes
    steps:
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint check
        run: npm run check:lint
      - name: Types check
        run: npm run check:types
      - name: Deploy
        uses: amondnet/vercel-action@v25
        id: vercel-deployment
        with:
          vercel-project-name: 'the-learning-path'
          vercel-token: ${{ secrets.VERCEL_ACCOUNT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: true
          github-deployment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      preview-url: ${{ steps.vercel-deployment.outputs.preview-url }}

  Test:
    runs-on: ubuntu-latest
    needs: Deploy
    timeout-minutes: 30 # to prevent a hanging process from using all CI minutes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ needs.Deploy.outputs.preview-url }}
        with:
          build: npm run build:packages # cypress.config.ts depends on read utils from @sherpa/data package
          project: apps/web
